Functions conditions added

diff --git a/.github/workflows/timeout-and-continue-on-error.yml b/.github/workflows/timeout-and-continue-on-error.yml
--- a/.github/workflows/timeout-and-continue-on-error.yml
+++ b/.github/workflows/timeout-and-continue-on-error.yml
@@ -7,6 +7,29 @@ jobs:
   timeout:
     runs-on: ubuntu-latest
     steps:
-      - name: Testing 
-        run: pwd
+      - name: Step 1  
+        run: sleep 10
+
+      - name: Step 2
+        id: step-2
+        run: exit 1
+
+      - name : Runs on Failure Step 2
+        if: failure() && steps.step-2.conclusion == 'failure'
+        run: echo 'Step 2 has failed'
       
+      - name: Run on Failure
+        if: failure()
+        run: echo 'Failure'
+      
+      - name: Runs on Success
+        if: success()
+        run: echo 'Runs oin Success'
+      
+      - name: Always Runs
+        if: always()
+        run: echo 'Always Runs'
+      
+      - name: Runs when Cancelled
+        if: cancelled()
+        run: echo 'Runs on Cancelled'
